import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header2 from "@/components/Header2";
import Image from "next/image";

export default function Coop() {
  const backgroundStyle = {
    backgroundSize: "cover",
    backgroundPosition: "center center",
    backgroundAttachment: "fixed",
    backgroundImage: 'url("/mint.jpg")', // Replace with the actual image path

    minHeight: "100vh",
  };

  return (
    <>
      <Head>
        <title>Crypto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div style={backgroundStyle} className="brightness-50 "></div>
        <Header2 />
        <div className="absolute z-40 w-full h-full top-0">
         
            <h1 className="pt-20 font-VT323 text-white text-7xl text-center">
            You're in the coop !
            </h1>
         
          <div className="pt-28 grid grid-cols-1 md:grid-cols-3 lg:grid-flow-row gap-6 font-VT323 text-white text-5xl mx-16 leading-10">
            <div className="p-4">
            You own X chickens.
            <p className="pt-12">Stake your NFTs to earn delicious $EGGS rewards.</p>
            </div>
            <div className=" p-4 text-center	">
             You own X foxes.
             <p className="pt-12">Stake your NFTs to try to steal the precious $EGGS</p>
          {/*   <button className=" border-2 border-black bg-white rounded-full text-xl text-black px-12 flex items-center">
                MINT
              </button> */}  
            </div>
            <div className="p-4 text-center">
            Must read before staking !
            <Image className="mx-auto" src="/book.png" width={160} height={160} />
            <p className="py-8">Your $EGGS balance : <br />77812,123 $EGGS</p>
            <Image className="mx-auto" src="/egg.png" width={140} height={140} />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
